version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: 'rabbitmq'
    container_name: 'rabbitmq'
    restart: always
    env_file:
      - ./.env-deploy
    ports:
        - 5672:5672
        - 15672:15672
    expose:
      - "5672"

  db:
    image: postgres:13-alpine3.16
    container_name: 'db'
    hostname: 'db'
    restart: always
    env_file:
      - ./.env-deploy
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database.ddl:/database.ddl
    ports:
      - "5432:5432"
    expose:
      - "5432"

  celery:
    build: .
    container_name: sheduler
    restart: always
    depends_on:
      - db
      - rabbitmq
    env_file:
      - ./.env-deploy

volumes:
  pgdata:
