name: Python application

on:
  pull_request:
    branches: [ main ]
    
jobs:
  build310:

    runs-on: ubuntu-latest

    steps:
   
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created pull_request:
          pull_request message: ${{ github.event.pull_request[0].message }}
          
          Repository: ${{ github.repository }}
          
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide
        pip install mypy
        pip install -r test/requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with wemake-python-styleguide
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
    # - name: Lint with mypy
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     mypy . --ignore-missing-imports --install-types --statistics
    
    - name: Test with unittest
      run: |
        python -m unittest

  build311:

    runs-on: ubuntu-latest

    steps:
  
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide
        pip install mypy
        pip install -r test/requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with wemake-python-styleguide
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
    # - name: Lint with mypy
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     mypy . --ignore-missing-imports --install-types --statistics
    
    - name: Test with unittest
      run: |
        python -m unittest
